#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Nov 11 23:18:25 EST 2023
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto bd608ffaa91d4ac0a56b64091608d056 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot fixed_16_16_multiplier_test_behav xil_defaultlib.fixed_16_16_multiplier_test -log elaborate.log
